spring:
  datasource:
    url: jdbc:h2:C:\SpringBoot_Projects\1\test-security2db-themeleaf\test-security2db-themeleaf\testdb
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true
  h2:
    console.enabled: true
server:
  port: 8084

